name: Generate Snake

on:
  schedule: 
    # execute every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: YashGajjar21
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the changes
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}

